### PR TITLE
Rework lib, fixed al KLC

### PR DESCRIPTION
**Pull request by jkriege2**
- reworked lib completely (except SIP-networks)
- has resistors sorted by type and series now (e.g. standard 0207, Axial-Power, Shunts, Bare-Metal-Strips, ...)
- has several different pitches for most types of resistors + vertical and horizontal
- full metadata (incl. datasheet links etz.)
- full 3D lib: https://github.com/KiCad/kicad-library/pull/898
- script-based: https://github.com/pointhi/kicad-footprint-generator/pull/18
- all conform to KLC

res1
res2
res3d1
res3d2
res3d3

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Great work - I'll await resolution of https://github.com/KiCad/kicad-library/pull/898

**Comment by jkriege2** [comment]
rename done + fixed some remaining KLC issues (all check out now!)

**Comment by SchrodingersGat** [comment]
Ping this one when we get https://github.com/KiCad/kicad-library/pull/898 merged :)

**Comment by jkriege2** [comment]
ping!

**Pull request merged**
