### PR TITLE
Add a 3d model for the Resistor_Horizontal_RM7mm

### PR DESCRIPTION
**Pull request by Fat-Zer**
Associated changes with https://github.com/KiCad/kicad-library/pull/408

### CODE REVIEW

**Comment by christf** [comment]
I was able to test the wrl-file. how can this module be tested?

**Comment by Fat-Zer** [comment]
@christf, I'm a bit confused, what exact troubles to you have with the model?

**Comment by jkriege2** [comment]
included here: https://github.com/KiCad/Resistors_THT.pretty/pull/18

**Comment by jkriege2** [comment]
fixed as noted!

**Pull request closed without merging**
