### PR TITLE
all symbols conform to KLC now

### PR DESCRIPTION
**Pull request by jkriege2**

### CODE REVIEW

**Comment by pointhi** [comment]
Please note that Courtyard clearance is 0.25mm

**Comment by jkriege2** [comment]
I will look into this ...

**Comment by jkriege2** [comment]
OK, I wrote a Python script that regenerates all these packages with correct settings (I hope):
- KLCs check out OK, 
- CrtYrd distance should be fine etz.

For some of the resistor size I oriented on this: http://sun-pec.com/Pics/VM/Dimensions-of-Carbon-Resistor.jpg

Here are the old (upper row(s)) and new (lower row(s)) packages

resistors_new

**Comment by SchrodingersGat** [comment]
This is great. From the image (https://cloud.githubusercontent.com/assets/11967523/19024292/fa6b281e-8900-11e6-881c-3d12dbc5c200.png) it looks like `Resistor_Horizontal_RM15mm` is missing F.Fab layer?

**Comment by jkriege2** [comment]
Just added he wrong comp to the screenshot. the component is fine ... I just saw that I have to change the width of the res15, which is also done now.

Ready to  pull?

JAN

**Comment by SchrodingersGat** [comment]
Almost - can you remove the .py file from the library? The library should really contain library files only - maybe submit the script as a PR to https://github.com/pointhi/kicad-footprint-generator

**Comment by jkriege2** [comment]
OK, done ... but wouldn't it be better to have the scripts in the library-repo (they are usually not large anyways), e.g. in a subdirectory "autoscripts" or "generatorscripts" ... Then it is easier to see that there is a script available to generate some of the components. I didn't find the scripts before someone pointed me at the footprint-generator-repo! This could really help preventing double-work.

Best,
JAN

**Comment by jkriege2** [comment]
I created a PR for the creator-script: https://github.com/pointhi/kicad-footprint-generator/pull/12

**Comment by CarlPoirier** [comment]
Great for the footprint generator! For these, can you fix the conflicts please?

**Comment by jkriege2** [comment]
conflicts fixed

**Comment by jkriege2** [comment]
@pointhi @CarlPoirier @SchrodingersGat 

Can this be merged?

**Comment by jkriege2** [comment]
I will do a more thorough work-over (script-based) of this lib and open a new PR then!

**Pull request closed without merging**
